version: '3.8'

services:
  # Base de données MongoDB
  mongodb:
    image: mongo:latest
    container_name: cesizen-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cesizen_dev
      - MONGO_INITDB_ROOT_PASSWORD=dev_password
      - MONGO_INITDB_DATABASE=cesizen_dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - cesizen-network

  # Backend Node.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cesizen-backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=5001
      - MONGO_URI=mongodb://cesizen_dev:dev_password@mongodb:27017/cesizen_dev?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-3600}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN:-604800}
    ports:
      - "5001:5001"
    networks:
      - cesizen-network

  # Frontend React (production build)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cesizen-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - cesizen-network
      
  # Frontend React (development mode avec hot-reload)
  frontend-dev:
    image: node:18-alpine
    container_name: cesizen-frontend-dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5001/api
    command: sh -c "npm install -g pnpm && pnpm install && pnpm run dev -- --host 0.0.0.0 --port 4000"
    networks:
      - cesizen-network

networks:
  cesizen-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
