name: 🐛 Rapport de Bug
description: Signaler un bug ou un problème
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de remplir ce rapport de bug !
  - type: input
    id: version
    attributes:
      label: Version
      description: Quelle version de l'application utilisez-vous ?
      placeholder: ex. v1.0.0
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environnement
      description: Dans quel environnement avez-vous rencontré ce problème ?
      options:
        - Développement
        - Test
        - Production
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Que s'est-il passé ?
      description: Décrivez le bug de manière claire et concise.
      placeholder: Décrivez le comportement observé et le comportement attendu.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Étapes pour reproduire
      description: Comment pouvons-nous reproduire ce bug ?
      placeholder: |
        1. Aller à '...'
        2. Cliquer sur '....'
        3. Faire défiler jusqu'à '....'
        4. Observer l'erreur
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs pertinents
      description: Copiez et collez les logs pertinents si disponibles.
      render: shell
  - type: textarea
    id: additional
    attributes:
      label: Informations supplémentaires
      description: Tout contexte supplémentaire sur le problème.
